baseURL = "https://computation.netlify.app/"
languageCode = "en-us"
title = "Computation Structures"
[menu]

  [[menu.main]]
    identifier = "Labs"
    name = "Labs"
    url = "/labs/"
    weight = -110

  [[menu.main]]
    identifier = "Notes"
    name = "Notes"
    url = "/notes/"
    weight = -100

[markup.goldmark.renderer]
unsafe= true
